# Generated by Django 5.1.7 on 2026-01-17 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bidding',
            fields=[
                ('bidding_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('bid_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bid_quantity', models.IntegerField()),
                ('created_time', models.CharField(max_length=100)),
                ('verdict', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('location', models.CharField(max_length=150)),
                ('delivery', models.CharField(max_length=200)),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('photo_url', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField()),
                ('description', models.CharField(max_length=500)),
                ('fssai_license', models.CharField(max_length=200)),
                ('organic_certified', models.CharField(max_length=200)),
                ('moisture', models.CharField(max_length=200)),
                ('crop_year', models.CharField(max_length=200)),
                ('packaging', models.CharField(max_length=200)),
                ('supply_capacity', models.CharField(max_length=200)),
                ('enddate', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=255)),
                ('photo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('verdict', models.CharField(max_length=20)),
                ('bidding', models.ForeignKey(db_column='bidding_id', on_delete=django.db.models.deletion.CASCADE, to='database.bidding')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='database.product')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='database.user')),
            ],
        ),
        migrations.AddField(
            model_name='bidding',
            name='product',
            field=models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='database.product'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('payment_method', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(max_length=20)),
                ('transaction_date', models.DateTimeField()),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, to='database.order')),
            ],
        ),
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('transportation_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('vehicle_number', models.CharField(max_length=20)),
                ('driver_name', models.CharField(max_length=100)),
                ('driver_phone', models.CharField(max_length=15)),
                ('start_latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('start_longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('destination_latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('destination_longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, to='database.order')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='database.user'),
        ),
        migrations.AddField(
            model_name='bidding',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='database.user'),
        ),
    ]
