# Generated by Django 5.1.7 on 2026-01-14 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_alter_user_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('location', models.CharField(max_length=150)),
                ('delivery', models.CharField(max_length=200)),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('photo_url', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField()),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='database.user')),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
